# $FreeBSD$

FILES=          README

NO_OBJ=
FILESDIR=       /etc/sysctl.d
FILESMODE=      755

.include <bsd.prog.mk>

DIR=	${SYSCTLDIR}
CONF=	README

MK=		../mk
include ${MK}/os.mk
include ${MK}/scripts.mk
